1: 1_busquedaBinaria.c
	clear
	gcc -Wall -g -o 1 1_busquedaBinaria.c
	./1
	rm 1

2: 2_busquedaEnPosicion.c
	clear
	gcc -Wall -g -o 2 2_busquedaEnPosicion.c
	./2
	rm 2

3: 3_median2Vectors.c
	clear
	gcc -Wall -g -o 3 3_median2Vectors.c
	./3
	rm 3

4: 4_mergeSortV1.c
	clear
	gcc -Wall -g -o 4 4_mergeSortV1.c
	./4
	rm 4

5: 5_mergeSortV2.c
	clear
	gcc -Wall -g -o 5 5_mergeSortV2.c
	./5
	rm 5

6: 6_quickSortV1.c
	clear
	gcc -Wall -g -o 6 6_quickSortV1.c
	./6
	rm 6

7: 7_quickSortV2.c
	clear
	gcc -Wall -g -o 7 7_quickSortV2.c
	./7
	rm 7

8: 8_subsecuenciaMaxima.c
	clear
	gcc -Wall -g -o 8 8_subsecuenciaMaxima.c
	./8
	rm 8
